services:
  postgres:
    container_name: adventure-book-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: adventure_book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - adventure_book_postgres_data:/var/lib/postgresql/data

volumes:
  adventure_book_postgres_data:
