spring:
  application:
    name: adventure-book

  datasource:
    url: jdbc:postgresql://localhost:5432/adventure_book
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true